#==== spring related ======#
spring:
   profiles:
      active: dev
   application:
    name: covid19-Rest

#==== connect to mysql ======#
   jpa: 
      hibernate:
         ddl-auto: update
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
   datasource:
      url: postgres://cykymjompzdids:f3aca4895acdf28d4baba8be75c77104d61bbbdb590d9f23cb72bb59d996eab3@ec2-34-204-22-76.compute-1.amazonaws.com:5432/daolqn7tndm42n
      username: cykymjompzdids 
      password: f3aca4895acdf28d4baba8be75c77104d61bbbdb590d9f23cb72bb59d996eab3
      driver-class-name: com.mysql.jdbc.Driver

#====== security ======# < ----------------------------- important?
   security:
      basic:
         enabled: true
      user:
         password: password

# ====== hibernate ====
#logging.level.org.hibernate.SQL=TRACE
#logging.level.org.hibernate.type=debug


#logging:
#   level:
#      org.hibernate.SQL: TRACE
#      org.hibernate.type: debug
#      org.springframework.security: DEBUG
